import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from 'fs';
import path from 'path';
import esbuildSvelte from "esbuild-svelte";
import { sveltePreprocess } from "svelte-preprocess";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Plugin to import JSON files as modules
const jsonPlugin = {
	name: 'json',
	setup(build) {
		build.onResolve({ filter: /\.json$/ }, args => ({
			path: path.resolve(args.resolveDir, args.path),
			namespace: 'json',
		}));
		build.onLoad({ filter: /.*/, namespace: 'json' }, async (args) => {
			const contents = await fs.promises.readFile(args.path, 'utf8');
			return {
				contents: `export default ${contents};`,
				loader: 'js',
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		jsonPlugin,
		esbuildSvelte({
			preprocess: sveltePreprocess(),
			compilerOptions: { css: "injected" }
		})
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
